
name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner to execute the workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_HUB_TOKEN }}  # Docker Hub Access Token

      - name: Build Docker image
        run: |
          echo "Using tag"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/your_repo_name:22f3002291 .
          docker tag ${{ secrets.DOCKER_USERNAME }}/your_repo_name:22f3002291 ${{ secrets.DOCKER_USERNAME }}/your_repo_name:latest

      - name: Push Docker image
        run: |
          echo "Pushing image with tag:"
          docker push ${{ secrets.DOCKER_USERNAME }}/your_repo_name:22f3002291
          docker push ${{ secrets.DOCKER_USERNAME }}/your_repo_name:latest
